---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "1028"
      port: 1028
      targetPort: 1028
  selector:
    io.kompose.service: backend

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    io.kompose.service: frontend

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/file-stage-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: kevinwutech/devops:api1.0
          name: backend
          ports:
            - containerPort: 1028
              hostPort: 1028
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/file-stage-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: kevinwutech/devops:web1.0
          name: frontend
          ports:
            - containerPort: 5173
              hostPort: 5173
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./argocd/argocd-app-config.yaml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/file-stage-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: kevinwutech/devops:proxy1.0
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/default.conf
              name: nginx-cm0
              readOnly: true
              subPath: default.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: default.conf
                path: default.conf
            name: nginx-cm0
          name: nginx-cm0

---
apiVersion: v1
data:
  default.conf: |-
    server {
      listen 80;
      server_name localhost;

      location / {
        proxy_pass http://host.docker.internal:5173;
      }

      location /api {
        proxy_pass http://host.docker.internal:1028;
      }

      location ~ /api/asset$ {
        client_max_body_size 100G;
        proxy_pass http://host.docker.internal:1028;
        limit_except POST {
          deny all;
        }
      }

      location /socket.io {
        proxy_pass http://host.docker.internal:1028;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0

