version: "3"
services:
  frontend:
    extends:
      file: ./client/compose.yaml
      service: web
  backend:
    extends:
      file: ./server/compose.yaml
      service: api
  nginx:
    extends:
      file: ./nginx/compose.yaml
      service: proxy
